rvm:
- 2.4.0
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_e1301b1e0dc6_key -iv $encrypted_e1301b1e0dc6_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "Travis Bot"
- git config --global user.email guanhwang2011@gmail.com
- cd ~
- git clone --depth=50 --branch=dev git@github.com:OnceMore2020/oncemore2020.github.io.git
  blogbuild
- cd blogbuild
- gem install bundler
- bundle install
script:
- jekyll build
after_success:
- git add --all
- git commit -m ":black_nib:Updated By Travis"
- git push -u origin HEAD:master --force
branches:
  only:
  - dev
